language: node_js python
node_js:
  - 14
sudo: required
services:
  - docker
before_install:
  - docker build -t empy .
script:
  - docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) empy npm run test