name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - uses: lovasoa/setup-emscripten@master
      with:
        emscripten-version: '1.38.47'
    - name: Deploy to gh-pages branch
      run: npm run deploy
